image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        deployment: production
        script:
          - cat ./deploy.sh | ssh root@opensacco.co.ke
          - echo "Deploy step finished"