INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (1, 0, 'Borrowers', 'borrowers', 'Access Borrowers Module');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (2, 1, 'View borrowers', 'borrowers.view', 'View borrowers');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (3, 1, 'Update borrowers', 'borrowers.update', 'Update Borrowers');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (4, 1, 'Delete borrowers', 'borrowers.delete', 'Delete borrowers');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (5, 1, 'Create borrowers', 'borrowers.create', 'Add new borrower');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (6, 0, 'Loans', 'loans', 'Access Loans Module');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (7, 6, 'Create Loans', 'loans.create', 'Create Loans');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (9, 6, 'Update Loans', 'loans.update', 'Update Loans');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (10, 6, 'Delete Loans', 'loans.delete', 'Delete Loans');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (11, 6, 'View Loans', 'loans.view', 'View Loans');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (12, 6, 'Loan Products', 'loans.products', 'Manage Loan Products');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (13, 6, 'Loan Fees', 'loans.fees', 'Manage Loan Fees');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (14, 6, 'Loan Schedule', 'loans.schedule', 'Manage loan schedule, including sending loan schedule emails');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (15, 0, 'Repayments', 'repayments', 'View Repayments Module');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (16, 15, 'View Repayments', 'repayments.view', 'View All repayments');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (17, 15, 'Create Repayments', 'repayments.create', 'Add Repayments');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (18, 15, 'Delete Repayments', 'repayments.delete', 'Delete Repayments');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (19, 15, 'Update Repayments', 'repayments.update', 'Update Repayments');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (20, 0, 'Payroll', 'payroll', 'Access Payroll Module');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (21, 20, 'View Payroll', 'payroll.view', 'View Payroll');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (22, 20, 'Update Payroll', 'payroll.update', 'Update Payroll');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (23, 20, 'Delete Payroll', 'payroll.delete', 'Delete Payroll');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (24, 20, 'Create Payroll', 'payroll.create', 'Create Payroll');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (25, 0, 'Expenses', 'expenses', 'Access Expenses Module');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (26, 25, 'View Expenses', 'expenses.view', 'View Expenses');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (27, 25, 'Create Expenses', 'expenses.create', 'Create Expenses');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (28, 25, 'Update Expenses', 'expenses.update', 'Update Expenses');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (29, 25, 'Delete Expenses', 'expenses.delete', 'Delete Expenses');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (30, 0, 'Other Income', 'other_income', 'Access Other Income Module');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (31, 30, 'View Other Income', 'other_income.view', 'View Other income');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (32, 30, 'Create Other Income', 'other_income.create', 'Create other income');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (33, 30, 'Update Other Income', 'other_income.update', 'Update Other Incom');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (34, 30, 'Delete Other Income', 'other_income.delete', 'Delete other income');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (35, 0, 'Collateral', 'collateral', 'Access Collateral Module');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (36, 35, 'View collateral', 'collateral.view', 'View Collateral');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (37, 35, 'Update Collateral', 'collateral.update', 'Update Collateral');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (38, 35, 'Create Collateral', 'collateral.create', 'Create Collateral');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (39, 35, 'Delete Collateral', 'collateral.delete', 'Delete Collateral');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (40, 0, 'Reports', 'reports', 'Access Reports Module');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (41, 0, 'Communication', 'communication', 'Access Communication Module');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (42, 41, 'Create Communication', 'communication.create', 'Send Emails & SMS');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (43, 41, 'Delete Communication', 'communication.delete', 'Delete Communication');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (44, 0, 'Custom Fields', 'custom_fields', 'Access Custom Fields Module');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (45, 44, 'View Custom Fields', 'custom_fields.view', 'View Custom fields');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (46, 44, 'Create Custom Fields', 'custom_fields.create', 'Create Custom Fields');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (47, 44, 'Custom Fields', 'custom_fields.update', 'Update Custom Fields');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (48, 44, 'Delete Custom Fields', 'custom_fields.delete', 'Delete Custom Fields');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (49, 0, 'Users', 'users', 'Access Users Module');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (50, 49, 'View Users', 'users.view', 'View Users ');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (51, 49, 'Create Users', 'users.create', 'Create users');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (52, 49, 'Update Users', 'users.update', 'Update Users');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (53, 49, 'Delete Users', 'users.delete', 'Delete Users');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (54, 49, 'Manage Roles', 'users.roles', 'Manage user roles');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (55, 0, 'Settings', 'settings', 'Manage Settings');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (56, 0, 'Audit Trail', 'audit_trail', 'Access Audit Trail');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (57, 0, 'Savings', 'savings', 'Access Savings Menu');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (58, 57, 'Create Savings', 'savings.create', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (59, 57, 'Update Savings', 'savings.update', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (60, 57, 'Delete Savings', 'savings.delete', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (61, 57, 'Create Savings Transaction', 'savings.transactions.create', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (62, 57, 'Update Savings Transaction', 'savings.transactions.update', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (63, 57, 'Delete Savings Transaction', 'savings.transactions.delete', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (64, 57, 'View Savings', 'savings.view', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (65, 57, 'View Savings Transaction', 'savings.transactions.view', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (66, 57, 'Manage Savings Products', 'savings.products', 'Manage Savings Products');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (67, 57, 'Manage Savings Fees', 'savings.fees', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (68, 6, 'Approve Loans', 'loans.approve', 'Approve Loans');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (69, 6, 'Disburse Loans', 'loans.disburse', 'Disburse Loans');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (70, 1, 'Approve Borrowers', 'borrowers.approve', 'Approve Borrowers');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (71, 6, 'Withdraw Loans', 'loans.withdraw', 'Withdraw Loans');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (72, 6, 'Write Off Loans', 'loans.writeoff', 'Write off Loans');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (73, 6, 'Reschedule Loans', 'loans.reschedule', 'Reschedule Loans');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (74, 0, 'Dashboard', 'dashboard', 'Access Dashboard');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (75, 74, 'Loans Released Monthly Graph', 'dashboard.loans_released_monthly_graph', 'Access Loans Released Monthly Graph');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (76, 74, 'Loans Collected Monthly Graph', 'dashboard.loans_collected_monthly_graph', 'Access Loans Collected Monthly Graph');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (77, 74, 'Registered Borrowers', 'dashboard.registered_borrowers', 'Access Registered Borrowers Statistics');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (78, 74, 'Total Loans Released', 'dashboard.total_loans_released', 'Access Total Loans Released');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (79, 74, 'Total Collections', 'dashboard.total_collections', 'Access Total Collections Statistics');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (80, 74, 'Total Disbursed Loans', 'dashboard.loans_disbursed', 'Access Total Disbursed Loans Statistics');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (81, 74, 'Total Loans Pending', 'dashboard.loans_pending', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (82, 74, 'Loans Approved', 'dashboard.loans_approved', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (83, 74, 'Loans Declined', 'dashboard.loans_declined', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (84, 74, 'Loans Closed', 'dashboard.loans_closed', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (85, 74, 'Loans Withdrawn', 'dashboard.loans_withdrawn', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (86, 74, 'Loans Written Off', 'dashboard.loans_written_off', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (87, 74, 'Loans Rescheduled', 'dashboard.loans_rescheduled', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (88, 6, 'Create Guarantor', 'loans.guarantor.create', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (89, 6, 'Update Guarantor', 'loans.guarantor.update', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (90, 6, 'Delete Guarantor', 'loans.guarantor.delete', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (91, 6, 'Guarantor Savings', 'loans.guarantor.savings', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (92, 0, 'Capital', 'capital', 'Access Capital');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (93, 92, 'View  Capital', 'capital.view', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (94, 92, 'Create Capital', 'capital.create', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (95, 92, 'Update Capital', 'capital.update', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (96, 92, 'Delete Capital', 'capital.delete', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (97, 0, 'Assets', 'assets', 'Access Assets Menu');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (98, 97, 'Create Assets', 'assets.create', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (99, 97, 'View Assets', 'assets.view', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (100, 97, 'Update Assets', 'assets.update', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (101, 97, 'Delete Assets', 'assets.delete', '');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (102, 0, 'Vehicles', 'vehicles', 'Access vehicles');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (103, 102, 'Create Vehicles', 'vehicles.create', 'Create vehicles');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (104, 102, 'Update Vehicles', 'vehicles.update', 'Update vehicles');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (105, 102, 'Delete Vehicles', 'vehicles.delete', 'Delete vehicles');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (106, 102, 'View Vehicles', 'vehicles.view', 'View vehicles');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (107, 0, 'Branches', 'branches', 'Access branches');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (108, 107, 'Create Branches', 'branches.create', 'Create branches');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (109, 107, 'Update Branches', 'branches.update', 'Update branches');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (110, 107, 'Delete Branches', 'branches.delete', 'Delete branches');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (111, 107, 'View Branches', 'branches.view', 'View branches');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (112, 1, 'Blacklist Borrowers', 'borrowers.blacklist', 'Blacklist borrowers');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (113, 1, ' Borrowers Groups', 'borrowers.groups', 'borrower groups');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (114, 0, 'Bank', 'bank', 'Access bank');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (115, 114, 'Create Bank', 'bank.create', 'Create bank');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (116, 114, 'Update Bank', 'bank.update', 'Update bank');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (117, 114, 'Delete Bank', 'bank.delete', 'Delete bank');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (118, 114, 'View Bank', 'bank.view', 'View bank');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (119, 0, 'Stock', 'stock', 'Access stock');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (120, 119, 'Create Stock', 'stock.create', 'Create stock');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (121, 119, 'Update Stock', 'stock.update', 'Update stock');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (122, 119, 'Delete Stock', 'stock.delete', 'Delete stock');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (123, 119, 'View Stock', 'stock.view', 'View stock');
INSERT INTO  permissions (id, parent_id, name, slug, description) VALUES (124, 107, 'Assign Branches', 'branches.assign', '');